server:
  port: 9000

spring:
  application:
    #应用名称
    name: Ruyi_Takeaway
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruyi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间

mybatis-plus:
  configuration:
    #address_book->AddressBook
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

ruyi:
  path: D:\04_test\ruyi_resources\

# 阿里云短信/ 请在其他配置文件中定义
sendMessage:
  accessKeyId: xxxxxxxx
  accessKeySecret: xxxxxxxxxx
  # 单位秒
  expirationTimeSecond: 300
  redisPrefix: redis_send_message_code_

redisCache:
  # 过期时间
  timeOut: 3600
  dishCachePrefix: dish_prefix_
  setmealCachePrefix: setmeal_prefix_
